// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-25 09:09:48
package dto

// CurrencyRecord Generated by sql2struct-0.0.5 at 2024-06-25 09:09:48
type GameLog struct {
	Day      string `json:"day" form:"day"`             // 流水id
	PlayerId int64  `json:"player_id" form:"player_id"` // 玩家id
	Pagination
}
