// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
package dto

// MerchantList Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
type MerchantList struct {
    Id int32 `json:"id"`
    Guid string `json:"guid"`
    Name string `json:"name"` //  商户名称
    Host string `json:"host"` // 站点域名
    ManageHost string `json:"manage_host"`
    Status int32 `json:"status"`
    CreateTime int32 `json:"create_time"`
    UpdateTime int32 `json:"update_time"`
}
