// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-26 09:55:14
package dto

// StatisticalDailySlave Generated by sql2struct-0.0.5 at 2024-06-26 09:55:14
type StatisticalDailySlave struct {
	Pagination
}
