// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-26 09:55:47
package dto

// StatisticalLogPlatform Generated by sql2struct-0.0.5 at 2024-06-26 09:55:47
type StatisticalLogPlatform struct {
	Pagination
}
