// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-26 09:55:55
package dto

// StatisticalLogGame Generated by sql2struct-0.0.5 at 2024-06-26 09:55:55
type StatisticalLogGame struct {
	Pagination
}
