// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-26 09:55:07
package dto

// StatisticalDaily Generated by sql2struct-0.0.5 at 2024-06-26 09:55:07
type StatisticalDaily struct {
	Pagination
}
