// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
package dto

// SysRoleUsersIds Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
type SysRoleUsersIds struct {
	RoleId  int64   `json:"role_id"`
	UserIds []int64 `json:"user_ids"`
}

// SysRoleUsers Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
type SysRoleUsers struct {
	RoleId int64 `json:"role_id"`
	UserId int64 `json:"user_id"`
}
