// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
package dto

// SysRolePermissions Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
type SysRolePermissions struct {
    Id int64 `json:"id"`
    RoleId int64 `json:"role_id"`
    PermissionId int64 `json:"permission_id"`
    CreateTime int32 `json:"create_time"`
    UpdateTime int32 `json:"update_time"`
}
