// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
package dto

// SysRoleUsers Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
type SysRoleUsers struct {
    Id int32 `json:"id"`
    RoleId int64 `json:"role_id"`
    UserId int64 `json:"user_id"`
    CreateTime int32 `json:"create_time"`
    UpdateTime int32 `json:"update_time"`
}
