// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
package dto

// SysRoleMenu Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
type SysRoleMenu struct {
    Id int64 `json:"id"`
    RoleId int64 `json:"role_id"`
    MenuId int64 `json:"menu_id"`
    CreateTime int32 `json:"create_time"`
    UpdateTime int32 `json:"update_time"`
}
