// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-26 09:56:12
package dto

// ReportWdChannel Generated by sql2struct-0.0.5 at 2024-06-26 09:56:12
type ReportWdChannel struct {
	Pid int32 `json:"pid"` // 通道id
	Pagination
}
