// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-26 09:56:05
package dto

// ReportPayChannel Generated by sql2struct-0.0.5 at 2024-06-26 09:56:05
type ReportPayChannel struct {
	Pid int32 `json:"pid"` // 通道id
	Pagination
}
