// Package dto
// Generated by sql2struct-0.0.5 at 2024-07-03 08:28:56
package dto

// UserFightReq Generated by sql2struct-0.0.5 at 2024-07-03 08:28:56
type UserFightReq struct {
	StartTime int64 `json:"start_time" form:"start_time"`
	EndTime   int64 `json:"end_time" form:"end_time"`
	PlayerId  int64 `json:"player_id" form:"player_id"` // 玩家id
	Pagination
}
