// Package dto
// Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
package dto

// User Generated by sql2struct-0.0.5 at 2024-06-19 07:59:34
type User struct {
    Id int64 `json:"id"`
    Guid string `json:"guid"`
    Username string `json:"username"`
    Password string `json:"password"`
    NickName string `json:"nick_name"`
    MerchantId int64 `json:"merchant_id"`
    Role string `json:"role"`
    Avatar string `json:"avatar"`
    Email string `json:"email"`
    Phone string `json:"phone"`
    IsMaster int32 `json:"is_master"`
    CreateTime int32 `json:"create_time"`
    UpdateTime int32 `json:"update_time"`
    LastLoginTime int32 `json:"last_login_time"`
}
