// Package dto
// Generated by sql2struct-0.0.5 at 2024-07-03 08:28:16
package dto

// UserBetReq Generated by sql2struct-0.0.5 at 2024-07-03 08:28:16
type UserBetReq struct {
	StartTime int64 `json:"start_time" form:"start_time"` // 开始时间（时间戳）
	EndTime   int64 `json:"end_time" form:"end_time"`     // 结束时间（时间戳）
	PlayerId  int64 `json:"player_id" form:"player_id"`   // 玩家id
	Pagination
}
