CREATE TABLE `game_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `record_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '记录id',
  `player_id` bigint NOT NULL DEFAULT '0' COMMENT '玩家id',
  `channel_id` int NOT NULL DEFAULT '0' COMMENT '渠道id',
  `platform_id` int NOT NULL DEFAULT '0' COMMENT '游戏平台id',
  `game_id` int NOT NULL DEFAULT '0' COMMENT '游戏id',
  `game_type` tinyint NOT NULL DEFAULT '0' COMMENT '游戏类型 0 slot 1 百人场 2 牌局 3 崩溃类',
  `level_id` int NOT NULL DEFAULT '0' COMMENT '场次id',
  `desk_id` bigint NOT NULL DEFAULT '0' COMMENT '桌子id',
  `desk_type` int NOT NULL DEFAULT '0' COMMENT '桌子类型',
  `reg_time` bigint NOT NULL DEFAULT '0' COMMENT '注册时间',
  `chip_rule` tinyint NOT NULL DEFAULT '0' COMMENT '打码规则 0:不打码 1:slot 2:brc 3:crash 4:poker',
  `chip` bigint NOT NULL DEFAULT '0' COMMENT '此局打码量',
  `balance` bigint NOT NULL DEFAULT '0' COMMENT '游戏后总余额',
  `cash` bigint NOT NULL DEFAULT '0' COMMENT '游戏后真金',
  `deposit` bigint NOT NULL DEFAULT '0' COMMENT '游戏后绑金',
  `bonus` bigint NOT NULL DEFAULT '0' COMMENT '游戏后bonus',
  `before_balance` bigint NOT NULL DEFAULT '0' COMMENT '游戏前总余额',
  `before_cash` bigint NOT NULL DEFAULT '0' COMMENT '游戏前真金',
  `before_deposit` bigint NOT NULL DEFAULT '0' COMMENT '游戏前绑金',
  `before_bonus` bigint NOT NULL DEFAULT '0' COMMENT '游戏前bonus',
  `recharge` bigint NOT NULL DEFAULT '0' COMMENT '总充值',
  `withdrawal` bigint NOT NULL DEFAULT '0' COMMENT '总提现',
  `bet` bigint NOT NULL DEFAULT '0' COMMENT '下注',
  `add_cash` bigint NOT NULL DEFAULT '0' COMMENT '赢真金',
  `add_deposit` bigint NOT NULL DEFAULT '0' COMMENT '赢绑金',
  `reward` bigint NOT NULL DEFAULT '0' COMMENT '返奖',
  `win` bigint NOT NULL DEFAULT '0' COMMENT '输赢值=返奖-下注-抽水',
  `fee` bigint NOT NULL DEFAULT '0' COMMENT '抽水',
  `is_free` tinyint NOT NULL DEFAULT '0' COMMENT '是否免费',
  `win_type` tinyint NOT NULL DEFAULT '0' COMMENT '赢奖类型 0=未赢，1=小赢，2=big win，3=mega win',
  `plan_id` tinyint NOT NULL DEFAULT '0' COMMENT '计划id',
  `control_log` text COLLATE utf8mb4_general_ci NOT NULL COMMENT '游戏日志',
  `result_log` text COLLATE utf8mb4_general_ci NOT NULL COMMENT '游戏结果',
  `ext_log` text COLLATE utf8mb4_general_ci NOT NULL COMMENT '游戏结果额外记录',
  `start_time` bigint NOT NULL DEFAULT '0' COMMENT '游戏开始时间',
  `end_time` bigint NOT NULL DEFAULT '0' COMMENT '游戏结束时间',
  `link_game_log` text COLLATE utf8mb4_general_ci COMMENT '游戏结果',
  `log_type` tinyint NOT NULL DEFAULT '0' COMMENT '日志分类 0=下注返奖日志 1=下注日志 2=返奖日志',
  PRIMARY KEY (`id`),
  KEY `IDX_game_log_20240627_game_id` (`game_id`),
  KEY `IDX_game_log_20240627_end_time` (`end_time`),
  KEY `IDX_game_log_20240627_record_id` (`record_id`),
  KEY `IDX_game_log_20240627_player_id` (`player_id`),
  KEY `IDX_game_log_20240627_channel_id` (`channel_id`),
  KEY `IDX_game_log_20240627_platform_id` (`platform_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
