CREATE TABLE `retain` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `channel_id` int unsigned NOT NULL DEFAULT '0' COMMENT '日期',
  `date` int unsigned NOT NULL DEFAULT '0' COMMENT '日期',
  `type` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '类型: 1登录,2注册,3充值,4提现',
  `num` int unsigned NOT NULL DEFAULT '0' COMMENT '人数',
  `r_2` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_3` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_4` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_5` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_6` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_7` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_14` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_30` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_45` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_60` decimal(9,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '留存',
  `r_2_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_3_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_4_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_5_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_6_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_7_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_14_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_30_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_45_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `r_60_num` int unsigned NOT NULL DEFAULT '0' COMMENT '留存数',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `search` (`type`,`channel_id`,`date`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1621 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='留存';
