CREATE TABLE `statistical_daily` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `register` int unsigned DEFAULT '0' COMMENT '日期区间内注册的账号数量',
  `login` int unsigned DEFAULT '0' COMMENT '日期区间内有过登录行为的账号数量',
  `active` int DEFAULT '0' COMMENT '日期区间内参与spin人数',
  `prepaid` int DEFAULT '0' COMMENT '日期区间内充值总额',
  `prepaid_count` int DEFAULT '0' COMMENT '充值笔数',
  `prepaid_number` int DEFAULT '0' COMMENT '日期区间内充值人数',
  `withdraw` int DEFAULT NULL COMMENT '日期区间内已提现成功金额',
  `withdraw_new` int DEFAULT '0' COMMENT '当天首次提现的人数',
  `withdraw_number` int DEFAULT '0' COMMENT '日期区间内已提现成功人数',
  `new_pay` int DEFAULT '0' COMMENT '新增付费人数+1',
  `win` bigint unsigned DEFAULT '0',
  `bet` bigint unsigned DEFAULT '0',
  `bet_real_time` bigint NOT NULL DEFAULT '0' COMMENT '实时投注',
  `win_real_time` bigint NOT NULL DEFAULT '0' COMMENT '实时赢奖情况',
  `coins` bigint DEFAULT '0' COMMENT '可提金币',
  `type` tinyint DEFAULT '0' COMMENT 'models',
  `time_int` int NOT NULL COMMENT '当天时间缀',
  `old_pay` int NOT NULL DEFAULT '0' COMMENT '付费老用户',
  `re_old_pay` decimal(6,2) NOT NULL COMMENT '老用户复购率',
  `first_recharge` int NOT NULL DEFAULT '0' COMMENT '当日首充人数',
  `first_recharge_total` bigint NOT NULL DEFAULT '0' COMMENT '当日首充用户充值总额',
  `channel_id` int DEFAULT '0' COMMENT '渠道id default(0)',
  `created_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `reg_black_list` int NOT NULL DEFAULT '0' COMMENT '当日注册关联黑名单数量',
  `active_avg_spin` int NOT NULL DEFAULT '0' COMMENT '新注册活跃平均spin次数',
  `active_avg_bet` bigint NOT NULL DEFAULT '0' COMMENT '新注册活跃平均下注',
  `time_tag` int NOT NULL DEFAULT '0' COMMENT '小时标识',
  `installs` int unsigned DEFAULT '0' COMMENT '总安装量',
  `fb_installs` int DEFAULT '0' COMMENT 'Facebook渠道安装量',
  `installs_update_status` tinyint DEFAULT '0' COMMENT '查询adjust安装信息状态 -1失败 0未更新 1更新成功',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `search_key` (`time_int`,`channel_id`) USING BTREE COMMENT '时间缀与渠道列表',
  KEY `channel_id` (`channel_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5875 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='每日数据报表(注册,活跃,充值=)';
