CREATE TABLE `t_player_profile` (
  `n_id` bigint NOT NULL AUTO_INCREMENT,
  `n_playerID` bigint unsigned NOT NULL COMMENT '玩家ID',
  `n_type` smallint NOT NULL DEFAULT '0' COMMENT '用户类型: 0=新手, 1=免费, 2=付费小R, 3=中R,4=大R，5=超R，33=黑名单用户',
  `n_tag` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '用户标签列表, 用,分隔。',
  `n_createTime` bigint DEFAULT '0' COMMENT '创建时间 单位秒',
  `n_score` bigint NOT NULL DEFAULT '0' COMMENT '信任评分',
  `n_updateTime` datetime DEFAULT NULL COMMENT '更新日期',
  `n_recharge_count` int DEFAULT '0' COMMENT '充值次数',
  `n_recharge_max` bigint DEFAULT '0' COMMENT '单次最大充值额',
  `n_channel` int DEFAULT '0' COMMENT '渠道号',
  `n_prev_pay` bigint DEFAULT '0' COMMENT '上次充值金额',
  `n_kind` smallint DEFAULT '0' COMMENT '用户风险种类: 0=A普通, 1=B可疑，2=C安全',
  `n_total_chip` bigint DEFAULT '0' COMMENT '总打码量',
  `n_chip_progress` bigint DEFAULT '0' COMMENT '打码进度',
  `n_chip_requirement` bigint DEFAULT '0' COMMENT '打码需求',
  `n_vip_level` int DEFAULT '0' COMMENT 'vip等级',
  `n_other` varchar(255) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '其他信息记录',
  `n_bonus_chip_progress` bigint DEFAULT '0' COMMENT 'bonus打码进度',
  `n_bonus_chip_requirement` bigint DEFAULT '0' COMMENT 'bonus打码需求',
  `n_mch_id` bigint DEFAULT '0' COMMENT '商户ID',
  PRIMARY KEY (`n_id`) USING BTREE,
  UNIQUE KEY `t_player_lucky_un` (`n_playerID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3279 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='玩家画像';
