CREATE TABLE `t_recharge_record` (
  `n_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `n_orderid` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单ID',
  `n_playerid` bigint unsigned DEFAULT NULL COMMENT '玩家ID',
  `n_amount` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '充值金额，小数点2位',
  `n_state` int DEFAULT NULL COMMENT '订单状态: 0=未付款, 1=已付款,2=已发货，3=补发成功， -1=充值失败，-2=发货失败',
  `n_des` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单失败描述',
  `n_createtime` datetime DEFAULT NULL COMMENT '订单创建时间',
  `n_paytime` datetime DEFAULT NULL COMMENT '订单付款时间',
  `n_finishtime` datetime DEFAULT NULL COMMENT '订单完成时间（发货成功或失败）',
  `n_coin` bigint DEFAULT NULL COMMENT '得到金币数',
  `n_channel` int DEFAULT NULL COMMENT '渠道号',
  `n_ex_orderid` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '外部订单号',
  `n_bankinfo` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '银行卡信息: 姓名和卡号, json',
  `n_ex_resp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '外部支付平台回复内容',
  `n_from` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付渠道',
  `n_phone` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '手机号',
  `n_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '姓名',
  `n_partnerid` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商户ID',
  `n_platform` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '充值平台',
  `n_goods_id` int DEFAULT '0' COMMENT '充值商品ID',
  `n_pic` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '转账截图列表(json格式)',
  `n_inviteID` bigint DEFAULT '0' COMMENT '邀请人玩家playerID',
  `n_topInvite` bigint DEFAULT '0' COMMENT '最高上级玩家id',
  `n_src` tinyint DEFAULT '1' COMMENT '来源ID： 1=商城按钮， 2=+号，3=充值优惠按钮， 4=登陆奖励入口， 5=月卡VIP， 6=匹配金币不足。',
  `n_input_type` tinyint DEFAULT '1' COMMENT '1=选择，2=手动输入',
  `n_client_type` tinyint DEFAULT '1' COMMENT '客户端类型: 1=APK，2=html5',
  `n_client_ver` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '客户端版本号',
  `n_entertime` datetime DEFAULT NULL COMMENT '进入商城页面时间',
  `n_before_coin` bigint DEFAULT '0' COMMENT '充值前的金币数',
  `n_open_src` tinyint DEFAULT '0' COMMENT '打开来源ID',
  `n_vpay_createtime` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '' COMMENT '回调createtime',
  `n_red` tinyint DEFAULT '0' COMMENT '红点状态',
  PRIMARY KEY (`n_id`) USING BTREE,
  UNIQUE KEY `t_recharge_record_un` (`n_orderid`) USING BTREE,
  KEY `t_recharge_record_n_playerid_IDX` (`n_playerid`) USING BTREE,
  KEY `t_recharge_record_n_createtime_IDX` (`n_createtime`) USING BTREE,
  KEY `t_recharge_record_n_paytime_IDX` (`n_paytime`) USING BTREE,
  KEY `vpay_createtime_IDX` (`n_vpay_createtime`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2386 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='充值记录表';
