mode: test

name: merchant
version: v0.1

zone: India

server:
  http:
    host: 0.0.0.0
    port: 8099

jwt:
  secret: gN9#kX
  token_expire: 24
  issuer: bz
  sub: bz

log:
  log_level: debug
  log_dir: ./log
  log_prefix: merchant
  max_size : 30

data:
  mysql-merchant:
    host: 127.0.0.1
    port: 3306
    user: back
    password: Back_789456123
    database: merchant
    max_idle: 20
    max_open: 20
    max_life_time: 300
  mysql-log:
    host: 127.0.0.1
    port: 3306
    user: back
    password: Back_789456123
    database: log
    max_idle: 20
    max_open: 20
    max_life_time: 300
  mysql-admin:
    host: 127.0.0.1
    port: 3306
    user: back
    password: Back_789456123
    database: admin
    max_idle: 20
    max_open: 20
    max_life_time: 300
  mysql-player:
    host: 127.0.0.1
    port: 3306
    user: back
    password: Back_789456123
    database: player
    max_idle: 20
    max_open: 20
    max_life_time: 300
  redis-merchant:
    addr: 127.0.0.1:6379
    password: YKpTDaSHjx
    database: 0
    max_active: 50
  clickhouse-log:
    host: 127.0.0.1
    port: 9000
    database: log
    user: default
    password: LgGqjwF6I43462T
    timeout_connect: 2
    timeout_query: 4

# nsq
nsq:
  addr: 127.0.0.1:4150
  lookUpdAddr:
    - 127.0.0.1:4161


url:
  third_order_check: http://127.0.0.1:9600