// Package po
// Generated by sql2struct-0.0.5 at 2024-06-19 10:57:54
package po

// SysPermissions Generated by sql2struct-0.0.5 at 2024-06-19 10:57:54
type SysPermissions struct {
    Id int64 `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
    MenuId int64 `gorm:"column:menu_id" json:"menu_id"` // 权限归属菜单
    Name string `gorm:"column:name" json:"name"` // 权限名称
    Code string `gorm:"column:code" json:"code"` // 标识
    Path string `gorm:"column:path" json:"path"`
    Command string `gorm:"column:command" json:"command"`
    CreateTime int32 `gorm:"column:create_time" json:"create_time"`
    UpdateTime int32 `gorm:"column:update_time" json:"update_time"`
}

func (s *SysPermissions) TableName() string {
    return "sys_permissions"
}
