// Package po
// Generated by sql2struct-0.0.5 at 2024-06-19 07:59:50
package po

// SysRoleMenu Generated by sql2struct-0.0.5 at 2024-06-19 07:59:50
type SysRoleMenu struct {
    Id int64 `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
    RoleId int64 `gorm:"column:role_id" json:"role_id"`
    MenuId int64 `gorm:"column:menu_id" json:"menu_id"`
    CreateTime int32 `gorm:"column:create_time" json:"create_time"`
    UpdateTime int32 `gorm:"column:update_time" json:"update_time"`
}

func (s *SysRoleMenu) TableName() string {
    return "sys_role_menu"
}
